project:
  type: book

book:
  title: ""
  author: ""
  date: ""
  search: true
  repo-url: https://github.com/eopf-toolkit/eopf-101
  page-navigation: true
  sidebar:
   search: true
   logo: "img/EOPF_FINAL_LOGO.png"
  page-footer:
    left: "Development Seed, thriveGEO and SparkGeo"
    center: "License: Apache 2.0"
    right:
      - icon: github
        href: https://github.com/eopf-toolkit/eopf-101

  chapters:
    - index.qmd
    - part: "**About EOPF**"
      chapters:
        - 01_about_eopf/11_about_eopf.qmd
        - 01_about_eopf/12_about_cloudoptimized_formats.qmd
        - 01_about_eopf/13_overview_eopf_datasets.qmd
    - part: "**About EOPF Zarr**"
      chapters:
       - 02_about_eopf_zarr/21_what_is_zarr.qmd
       - 02_about_eopf_zarr/22_zarr_structure_S1GRD.ipynb
       - 02_about_eopf_zarr/23_S1_basic_operations.ipynb
       - 02_about_eopf_zarr/24_zarr_struct_S2L2A.ipynb
       - 02_about_eopf_zarr/25_zarr_struct_S3.ipynb
    - part: "**About Chunking**"
      chapters:
       - 03_about_chunking/31_zarr_chunking_intro.qmd
       - 03_about_chunking/32_zarr_chunking_strat.qmd
    - part: "**EOPF and STAC**"
      chapters:
        - 04_eopf_and_stac/41_stac_intro.qmd
        - 04_eopf_and_stac/42_eopf_stac_zarr_tutorial.qmd
        - 04_eopf_and_stac/43_eopf_stac_connection.ipynb
        - 04_eopf_and_stac/44_eopf_stac_xarray_tutorial.ipynb
    - part: "**Tools to work with EOPF Zarr**"
      chapters:
        - 05_zarr_tools/51_eopf_stac_r.qmd
        - 05_zarr_tools/52_eopf_stac_qgis.qmd
        - 05_zarr_tools/53_eopf_zarr_r.qmd
        - 05_zarr_tools/54_eopf_zarr_r_examples.qmd
        - 05_zarr_tools/57_rstac_gdalcubes.qmd
        # - 05_zarr_tools/55_titiler.qmd
        
    - part: "**EOPF Zarr in Action**"
      chapters:
        - 06_eopf_zarr_in_action/61_sardinia_s2_tfci.ipynb
        - 06_eopf_zarr_in_action/62_sardinia_s3_lst.ipynb
        - 06_eopf_zarr_in_action/63_sardinia_dNBR.ipynb
        - 06_eopf_zarr_in_action/64_flood_mapping_valencia.ipynb
        - 06_eopf_zarr_in_action/65_create_overviews.ipynb
        - 06_eopf_zarr_in_action/66_use_overviews.ipynb
        - 06_eopf_zarr_in_action/67_reservoir_surface_monitoring.ipynb
        - 06_eopf_zarr_in_action/68_vegetation_anomalies.ipynb
        - 06_eopf_zarr_in_action/69_coastal_water_dynamics_s1.ipynb
        # - 06_eopf_zarr_in_action/69_ 
    
    - glossary.qmd
    - references.qmd

execute:
  eval: true
  timeout: 300
  error: false
  warning: false

format:
  html:
    number-sections: false
    theme:
      - cosmo
      - brand
    include-in-header: "plausible.html"
