channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.5.2
  - r-rstac=1.0.1
  - r-tidyverse=2.0.0
  - r-stars=0.7-0
  - r-terra=1.8-93
  - r-httr2=1.2.2
  - r-fs=1.6.6
  - r-lobstr=1.1.3
  - r-biocmanager
  - sqlite=3.51.2
  - r-sf=1.0-22
  - r-gdalcubes=0.7.2
  - r-viridis=0.6.5
  # - bioconductor-rarr==1.10.1 - Currently not supported in bioconda so installed manually in Dockerfile_r
